# Generated by Django 5.1.5 on 2025-01-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
    ]
