# Generated by Django 5.1.5 on 2025-01-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_user_alter_page_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table='pages',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
