# Generated by Django 5.1.5 on 2025-01-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_alter_page_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.URLField(),
        ),
    ]
