# Generated by Django 5.1.5 on 2025-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_alter_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_image/'),
        ),
    ]
